export const CardData = [
    {
      imgSrc: "./src/assets/home3.jpeg",
      text: "Street 43/Brooklyn",
      bed: 6,
      bath: 4,
      title: "Brooklyn",
      price: "€ 680.499,00",
      buttonText: "Buy",
      videoSrc: "./src/assets/video4.mp4",
      animation: "left",
    },
    {
      imgSrc: "./src/assets/foto-5.jpg",
      text: "Street 767/NewYork",
      bed: 4,
      bath: 3,
      title: "New York",
      price: "€ 918.350,00",
      buttonText: "Buy",
      videoSrc: "./src/assets/video7.mp4",
      animation: "right",
    },
    {
      imgSrc: "./src/assets/home1.jpeg",
      text: "Street 86/France",
      bed: 6,
      bath: 5,
      title: "Paris",
      price: "€ 874.590,00",
      buttonText: "Buy",
      videoSrc: "./src/assets/video6.mp4",
      animation: "up",
    },
    {
      imgSrc: "./src/assets/house1.jpeg",
      text: "Street 43/Brooklyn",
      bed: 6,
      bath: 4,
      title: "Brooklyn",
      price: "€ 680.499,00",
      buttonText: "Buy",
      videoSrc: "./src/assets/video1.mp4",
      animation: "down",
    },
    {
      imgSrc: "./src/assets/foto-2.jpg",
      text: "Street 767/NewYork",
      bed: 4,
      bath: 3,
      title: "New York",
      price: "€ 918.350,00",
      buttonText: "Buy",
      videoSrc: "./src/assets/video4.mp4",
      animation: "right",
    },
    {
      imgSrc: "./src/assets/house3.jpeg",
      text: "Street 86/France",
      bed: 6,
      bath: 5,
      title: "Paris",
      price: "€ 874.590,00",
      buttonText: "Buy",
      videoSrc: "./src/assets/video3.mp4",
      animation: "left",
    },
  ];
  