export const CardData = [
    {
      imgSrc: "/home3.jpeg",
      text: "Street 43/Brooklyn",
      bed: 6,
      bath: 4,
      title: "Brooklyn",
      price: "€ 680.499,00",
      buttonText: "Buy",
      videoSrc: "/video4.mp4",
      animation: "left",
    },
    {
      imgSrc: "/foto-5.jpg",
      text: "Street 767/NewYork",
      bed: 4,
      bath: 3,
      title: "New York",
      price: "€ 918.350,00",
      buttonText: "Buy",
      videoSrc: "/video7.mp4",
      animation: "right",
    },
    {
      imgSrc: "/home1.jpeg",
      text: "Street 86/France",
      bed: 6,
      bath: 5,
      title: "Paris",
      price: "€ 874.590,00",
      buttonText: "Buy",
      videoSrc: "/video6.mp4",
      animation: "up",
    },
    {
      imgSrc: "/house1.jpeg",
      text: "Street 43/Brooklyn",
      bed: 6,
      bath: 4,
      title: "Brooklyn",
      price: "€ 680.499,00",
      buttonText: "Buy",
      videoSrc: "/video1.mp4",
      animation: "down",
    },
    {
      imgSrc: "/foto-2.jpg",
      text: "Street 767/NewYork",
      bed: 4,
      bath: 3,
      title: "New York",
      price: "€ 918.350,00",
      buttonText: "Buy",
      videoSrc: "/video4.mp4",
      animation: "right",
    },
    {
      imgSrc: "/house3.jpeg",
      text: "Street 86/France",
      bed: 6,
      bath: 5,
      title: "Paris",
      price: "€ 874.590,00",
      buttonText: "Buy",
      videoSrc: "/video3.mp4",
      animation: "left",
    },
  ];
  